version: '3.8'

services:
  app:
    image: ghcr.io/neooriginal/howclosetoworldend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    volumes:
      - app_logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_logs: 